error: fix extract_resource
The resource name is extracted with the URL and the resource in URL is
always in the plurial. So we need to convert the resource to singular
before returning the result.

Normally, the REST API should return this information in the singular
form ...